### ISSUE TITLE
Cause vim stuck while typing

### ISSUE THREAD

**Issue by ghost** [prabirshrestha/asyncomplete-buffer.vim#2]
This plugin kill my vim, `updatetime=4000`, not responding, tons of `[buffer]` entries as candidates.

**Comment by niklaas** [comment]
Same here.

Is it possible to exclude certain buffers as references for completion?

I thought about `blacklist` when registering with `asyncomplete#register_source` but as far as I understand this is for deactivating all buffer sources for specific filetypes.

**Comment by prabirshrestha** [comment]
Buffer algorithm is definitely not so good as I would like it to be. If anyone has a better algorithm let me know.

If you have python enabled vim we could also support starting a thread and letting it do much of the computations so vim remains responsive.

**Comment by niklaas** [comment]
Thanks for your response. I finally decided against buffers as completion source. Apart from long response times, the suggestions by buffers cluttered the completion dialog a lot. I have a much better experience with `vim-lsp` only.

**Comment by Holzhaus** [comment]
I think we should go for the python solution then.

**Comment by jsit** [comment]
This is because the `TextChangedI` causes the buffer source to refresh _waaayyyy_ too often. After #4 is merged, you can override the events in your source registration in `.vimrc` with something like this:

```vim
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
	\ 'name': 'buffer',
	\ 'whitelist': ['*'],
	\ 'blacklist': ['go'],
	\ 'events': ['TextChanged','InsertLeave','BufWinEnter','BufWritePost'],
	\ 'completor': function('asyncomplete#sources#buffer#completor'),
	\ }))
```

#1 could be solved by this, as well.

**Comment by ghost** [comment]
It's perfect now, but I have to explicitly enable `let g:asyncomplete_buffer_clear_cache = 1` in vimrc. Cheers! Thanks.

**Comment by jsit** [comment]
@tuyenpm9 It defaults to `1`
